---

apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: Opaque
data:
  INFLUXDB_DB: bXlkYXRhYmFzZQ==  # "mydatabase" en base64
  INFLUXDB_USER: aW5mbHV4dXNlcg==  # "influxuser" en base64
  INFLUXDB_PASSWORD: aW5mbHV4cGFzc3dvcmQ=  # "influxpassword" en base64
  INFLUXDB_ADMIN_USER: YWRtaW4=  # "admin" en base64
  INFLUXDB_ADMIN_PASSWORD: YWRtaW5wYXNzd29yZA==  # "adminpassword" en base64
