---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteo-deployment
  labels:
    app: meteo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meteo
  template:
    metadata:
      labels:
        app: meteo
    spec:
      containers:
      - name: meteo
        image: pockost/telegraf-cf-weather:arm
        env:
          - name: INFLUXDB_HOST
            value: "influxdb"
          - name: INFLUXDB_USER
            valueFrom:
              secretKeyRef:
                name: influxdb-secret
                key: INFLUXDB_USER
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influxdb-secret
                key: INFLUXDB_PASSWORD
          - name: INFLUXDB_DB
            valueFrom:
              secretKeyRef:
                name: influxdb-secret
                key: INFLUXDB_DB
          - name: INFLUXDB_PORT
            value: "8086"
        ports:
          - containerPort: 8125
