---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteo-deployment
  labels:
    app: meteo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meteo
  template:
    metadata:
      labels:
        app: meteo
    spec:
      containers:
      - name: meteo
        image: pockost/telegraf-cf-weather:arm
        env:
          - name: INFLUXDB_HOST
            value: "influxdb-service"
          - name: INFLUXDB_PORT
            value: "8086"
          - name: INFLUXDB_USER
            value: "influxuser"
          - name: INFLUXDB_PASSWORD
            value: "influxpassword"
          - name: INFLUXDB_NAME
            value: "mydatabase"
        ports:
          - containerPort: 8125
